### ISSUE TITLE
Nightly tests

### ISSUE THREAD

**Issue by Avsecz** [cschin/kipoi_model_zoo_dx#3]
The goal would be to have nightly integration tests: kipoi <-> DNAnexus

## Todo

- authentification
  - through API?
  - [ ] setup one example using an environment variable: DX_KEY to start the job
- install the user interface on circleci
  - which base docker image to use?
    - alpine/python/conda/ubuntu image?
- launch different jobs
  - have a for loop looping through few models
- hook everything together into CircleCi

**Comment by Avsecz** [comment]
## Tests

### notebooks
Execute the notebooks
```
jupyter nbconvert --to notebook --execute mynotebook.ipynb
```
http://nbconvert.readthedocs.io/en/latest/execute_api.html

### score_variants
Run a few batch commands, compare the produced output with the expected one

**Comment by cschin** [comment]
see the latest commit https://github.com/cschin/kipoi_model_zoo_dx/commit/76560a9d0921d1506d07bd6b4a10aa90a26a0530

The Dockerfile builds an image that can submit the variant effect testing jobs.  Please see if it is possible to integrate with circle.io cron jobs.  If you need some interface change for deploying the docker image on circle.io. Just make a PR or let me know what is the better way to do it.

**Comment by cschin** [comment]
once we are happy with the docker image setup, we can start to think the proper nightly testing cases.

**Comment by Avsecz** [comment]
Looks good! The only thing remaining is to:
- [ ] have some sort of feedback mechanism from batch submission script. Ideally, the script would wait for feedback till completion and then exit either with code 0 (success) or >=1 (failure). That way, the error reporting would be directly handled by circleci. Otherwise, one would need to manually setup the email sending when things fail etc.
- [ ] setup a test-user on the DNAnexus platform to get the testing API for circleCi
